services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - OPENSEARCH_INITIALIZE_PLUGINS=true
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - ueba-net
    restart: unless-stopped

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - opensearch
    networks:
      - ueba-net
    restart: unless-stopped

  data-prepper:
    image: opensearchproject/data-prepper:latest
    container_name: data-prepper
    depends_on:
      - opensearch
    ports:
      - "2021:2021"
    volumes:
      - ./data-prepper/pipelines/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper/config/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    networks:
      - ueba-net
    restart: unless-stopped

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    depends_on:
      - data-prepper
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/input_syslog.log:/fluent-bit/input_syslog.log
    networks:
      - ueba-net
    restart: unless-stopped

networks:
  ueba-net:
    driver: bridge
